name: magic_card
description: MTG-Card renderer, and utility package.
repository: https://github.com/ArcaneArts/magic_card
version: 1.0.1+dev.5
environment:
  sdk: ^3.3.2
dependencies:
  flutter:
    sdk: flutter
  foil: ^0.9.0+1
  memcached: ^1.0.2
  scryfall_api: ^2.0.0
  xl: ^0.9.1
  fast_log: ^1.0.7

dev_dependencies:
  lints: ^3.0.0
flutter: