// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJwUfXJ4hHspOtzqPkLCoLCCgXOLzgKw',
    appId: '1:774038668608:web:a8db1d046cac196a68e6a5',
    messagingSenderId: '774038668608',
    projectId: 'the-collector-app',
    authDomain: 'the-collector-app.firebaseapp.com',
    storageBucket: 'the-collector-app.appspot.com',
    measurementId: 'G-3SEJDY4FP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJcFsOTDE0E02-Cy2BZkF4sZh4gMV6MI',
    appId: '1:774038668608:android:b5846ed2c5a4c93f68e6a5',
    messagingSenderId: '774038668608',
    projectId: 'the-collector-app',
    storageBucket: 'the-collector-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqtsAIFG9eNdamnrreUmiZSlN1Q3GlDI',
    appId: '1:774038668608:ios:e57995e1d426160168e6a5',
    messagingSenderId: '774038668608',
    projectId: 'the-collector-app',
    storageBucket: 'the-collector-app.appspot.com',
    iosBundleId: 'com.example.modelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtqtsAIFG9eNdamnrreUmiZSlN1Q3GlDI',
    appId: '1:774038668608:ios:e671cdbe075173c868e6a5',
    messagingSenderId: '774038668608',
    projectId: 'the-collector-app',
    storageBucket: 'the-collector-app.appspot.com',
    iosBundleId: 'com.example.modelApp.RunnerTests',
  );
}
