name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.19.x'
          channel: 'beta' # Required for web

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Navigate to project directory
        run: cd the_collector

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Download Dependencies
        working-directory: the_collector
        run: flutter pub get

      - name: Build
        working-directory: the_collector
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the_collector/build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'